# k8s/moj-servis/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moj-servis
  namespace: agilni1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moj-servis
  template:
    metadata:
      labels:
        app: moj-servis
    spec:
      containers:
      - name: moj-servis
        image: git.fpmoz.sum.ba/mirko416/moj-servis:1.0
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
