# k8s/moj-servis/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: agilni-vjezba-svc
  namespace: agilni1
spec:
  selector:
    app: agilni-vjezba
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: NodePort
